
import React from 'react';
import { PricingCard } from './pricing/PricingCard';
import { useInView } from 'react-intersection-observer';
import { Check, ArrowRight, MessageSquareMore } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { useIsMobile } from '@/hooks/use-mobile';

export function PricingSection() {
  const { ref, inView } = useInView({
    threshold: 0.1,
    triggerOnce: true,
  });
  const isMobile = useIsMobile();

  const pricingPlans = [
    {
      title: "Starter",
      price: "$19",
      description: "per month",
      features: [
        "10 credits included monthly",
        "Upload content in any format",
        "Basic automatic transcription",
        "Articles up to 500 words",
        "Plain text export"
      ]
    },
    {
      title: "Professional",
      price: "$49",
      description: "per month",
      features: [
        "50 credits included monthly",
        "All basic features",
        "Advanced multilingual transcription",
        "Articles up to 2000 words",
        "Editorial style customization",
        "WordPress and multi-format export",
        "Priority support"
      ],
      popular: true
    },
    {
      title: "Team",
      price: "$99",
      description: "per month",
      features: [
        "200 credits included monthly",
        "All professional features",
        "No word limit for articles",
        "Multi-user access (up to 5)",
        "Advanced editorial style training",
        "API for custom integrations",
        "Dedicated account manager"
      ]
    },
    {
      title: "Enterprise",
      price: "Custom",
      description: "tailored plan",
      features: [
        "Customized solution for your company",
        "Unlimited credits",
        "Unlimited team access",
        "Dedicated training",
        "Custom integrations",
        "24/7 VIP support"
      ],
      isCustom: true
    }
  ];

  return (
    <section ref={ref} className="bg-gradient-to-b from-white to-gray-50 py-16 md:py-24 border-y border-gray-200 overflow-hidden">
      <div className="container mx-auto px-4">
        <div className={`max-w-3xl mx-auto text-center mb-12 md:mb-16 transition-all duration-1000 transform ${
          inView ? 'translate-y-0 opacity-100' : 'translate-y-20 opacity-0'
        }`}>
          <h2 className="text-3xl md:text-4xl font-playfair font-bold mb-4 md:mb-6 text-black">Invest in Your Journalism Future</h2>
          <p className="text-base md:text-lg text-gray-600">
            Choose the plan that best fits your editorial operation's size and needs.
            Each credit equals one complete article generated by the platform.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 md:gap-8 relative">
          {/* Background decoration */}
          <div className="absolute inset-0 bg-gradient-to-r from-transparent via-black/5 to-transparent opacity-50 -skew-y-6 -z-10"></div>
          
          {pricingPlans.map((plan, index) => (
            <div
              key={index}
              className={`transition-all duration-700 transform ${
                inView ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'
              }`}
              style={{ transitionDelay: `${index * 200}ms` }}
            >
              <PricingCard {...plan} />
            </div>
          ))}
        </div>

        <div className="mt-12 md:mt-16 text-center">
          <Link to="/dashboard">
            <Button 
              size={isMobile ? "default" : "lg"} 
              className="bg-black text-white hover:bg-gray-900 font-medium rounded-md px-6 flex items-center gap-2 mx-auto transform transition-all duration-300 hover:scale-105 hover:-translate-y-1 h-12 md:h-14"
            >
              Try It Now
              <ArrowRight className="w-5 h-5 animate-pulse" />
            </Button>
          </Link>
        </div>

        <div className={`mt-12 max-w-4xl mx-auto bg-gray-50 rounded-2xl p-6 md:p-8 border border-gray-200 shadow-sm transition-all duration-1000 delay-700 transform ${
          inView ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'
        }`}>
          <h3 className="text-xl font-bold mb-6 text-center">Frequently Asked Questions</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-bold mb-2 flex items-center gap-2 text-sm md:text-base">
                <Check className="w-4 h-4 md:w-5 md:h-5 text-black" />
                What is a credit?
              </h4>
              <p className="text-gray-600 text-xs md:text-sm">A credit allows you to generate a complete article from your provided content, including transcription, title generation, and body text.</p>
            </div>
            <div>
              <h4 className="font-bold mb-2 flex items-center gap-2 text-sm md:text-base">
                <Check className="w-4 h-4 md:w-5 md:h-5 text-black" />
                Do credits accumulate?
              </h4>
              <p className="text-gray-600 text-xs md:text-sm">Yes! Unused credits roll over to the next month, up to a maximum of three times your monthly plan.</p>
            </div>
            <div>
              <h4 className="font-bold mb-2 flex items-center gap-2 text-sm md:text-base">
                <Check className="w-4 h-4 md:w-5 md:h-5 text-black" />
                How does style training work?
              </h4>
              <p className="text-gray-600 text-xs md:text-sm">You provide examples of your ideal editorial style, and our AI learns to replicate that tone and approach in all generated content.</p>
            </div>
            <div>
              <h4 className="font-bold mb-2 flex items-center gap-2 text-sm md:text-base">
                <Check className="w-4 h-4 md:w-5 md:h-5 text-black" />
                Can I change plans?
              </h4>
              <p className="text-gray-600 text-xs md:text-sm">Absolutely! You can upgrade or downgrade your plan anytime, with adjustments reflected in your next billing cycle.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
