
export type Language = 'en' | 'pt';

export const translations = {
  en: {
    // Header translations
    login: "Login",
    createAccount: "Create Account",
    new: "New",
    settings: "Settings",
    logout: "Logout",
    search: "Search...",
    registerButton: "Create Account",
    dashboard: "Dashboard",
    
    // Landing page translations
    heroRevolutionizing: "Revolutionizing journalism",
    heroTitle: "Transform ideas into articles in seconds",
    heroDescription: "Create professional journalistic content 10x faster with PRESS AI, the tool that combines artificial intelligence with your editorial expertise to redefine your workflow.",
    tryItNow: "Try It Now",
    journalistsCount: "300+ journalists already using it",
    
    // Features section
    featuresTitle: "From Idea to Final Article in Minutes",
    featuresSubtitle: "An intelligent workflow that transforms any material into impeccable journalistic content, maintaining your editorial voice and saving hours of your day.",
    
    // Pricing section
    pricingTitle: "Invest in Your Journalism Future",
    pricingSubtitle: "Choose the plan that best fits your editorial operation's size and needs. Each credit equals one complete article generated by the platform.",
    planStarter: "Starter",
    planPro: "Professional",
    planTeam: "Team",
    planEnterprise: "Enterprise",
    perMonth: "per month",
    faqTitle: "Frequently Asked Questions",
    whatIsCredit: "What is a credit?",
    creditDesc: "A credit allows you to generate a complete article from your provided content, including transcription, title generation, and body text.",
    doCreditsAccumulate: "Do credits accumulate?",
    creditsAccDesc: "Yes! Unused credits roll over to the next month, up to a maximum of three times your monthly plan.",
    howStyleWorks: "How does style training work?",
    styleDesc: "You provide examples of your ideal editorial style, and our AI learns to replicate that tone and approach in all generated content.",
    canChangePlans: "Can I change plans?",
    changePlansDesc: "Absolutely! You can upgrade or downgrade your plan anytime, with adjustments reflected in your next billing cycle.",
    contactUs: "Contact Us",
    chooseThis: "Choose",
    
    // Media companies section
    mediaCompaniesTitle: "Trusted by Leading Media Companies",
    
    // Team section
    ourTeam: "Our Team",
    executiveDirector: "Executive Director",
    marketingDirector: "Marketing Director",
    operationsDirector: "Operations Director",
    
    // Footer translations
    company: "Company",
    about: "About",
    careers: "Careers",
    contact: "Contact",
    legal: "Legal",
    terms: "Terms",
    privacy: "Privacy",
    cookies: "Cookies",
    product: "Product",
    features: "Features",
    blog: "Blog",
    transformingJournalism: "Transforming journalism with AI",
    allRightsReserved: "All rights reserved"
  },
  pt: {
    // Header translations
    login: "Entrar",
    createAccount: "Criar Conta",
    new: "Novo",
    settings: "Configurações",
    logout: "Sair",
    search: "Pesquisar...",
    registerButton: "Criar Conta",
    dashboard: "Painel",
    
    // Landing page translations
    heroRevolutionizing: "Revolucionando o jornalismo",
    heroTitle: "Transforme ideias em artigos em segundos",
    heroDescription: "Crie conteúdo jornalístico profissional 10x mais rápido com PRESS AI, a ferramenta que combina inteligência artificial com sua experiência editorial para redefinir seu fluxo de trabalho.",
    tryItNow: "Experimente Agora",
    journalistsCount: "Mais de 300 jornalistas já utilizam",
    
    // Features section
    featuresTitle: "Da Ideia ao Artigo Final em Minutos",
    featuresSubtitle: "Um fluxo de trabalho inteligente que transforma qualquer material em conteúdo jornalístico impecável, mantendo a voz editorial e economizando horas do seu dia.",
    
    // Pricing section
    pricingTitle: "Invista no Futuro do seu Jornalismo",
    pricingSubtitle: "Escolha o plano que melhor se adapta ao tamanho e necessidades da sua operação editorial. Cada crédito equivale a um artigo completo gerado pela plataforma.",
    planStarter: "Inicial",
    planPro: "Profissional",
    planTeam: "Equipe",
    planEnterprise: "Empresarial",
    perMonth: "por mês",
    faqTitle: "Perguntas Frequentes",
    whatIsCredit: "O que é um crédito?",
    creditDesc: "Um crédito permite gerar um artigo completo a partir do seu conteúdo, incluindo transcrição, geração de título e texto.",
    doCreditsAccumulate: "Os créditos acumulam?",
    creditsAccDesc: "Sim! Créditos não utilizados acumulam para o próximo mês, até um máximo de três vezes seu plano mensal.",
    howStyleWorks: "Como funciona o treino de estilo?",
    styleDesc: "Você fornece exemplos do seu estilo editorial ideal, e nossa IA aprende a replicar esse tom e abordagem em todo o conteúdo gerado.",
    canChangePlans: "Posso mudar de plano?",
    changePlansDesc: "Claro! Você pode fazer upgrade ou downgrade do seu plano a qualquer momento, com ajustes refletidos no próximo ciclo de faturamento.",
    contactUs: "Entre em Contato",
    chooseThis: "Escolher",
    
    // Media companies section
    mediaCompaniesTitle: "Utilizado por Empresas Líderes de Mídia",
    
    // Team section
    ourTeam: "Nossa Equipe",
    executiveDirector: "Diretor Executivo",
    marketingDirector: "Diretora de Marketing",
    operationsDirector: "Diretor de Operações",
    
    // Footer translations
    company: "Empresa",
    about: "Sobre",
    careers: "Carreiras",
    contact: "Contato",
    legal: "Legal",
    terms: "Termos",
    privacy: "Privacidade",
    cookies: "Cookies",
    product: "Produto",
    features: "Recursos",
    blog: "Blog",
    transformingJournalism: "Transformando o jornalismo com IA",
    allRightsReserved: "Todos os direitos reservados"
  }
};
